services:
  postgres:
    image: postgres:15
    container_name: postgres-container-orchestrator
    environment:
      POSTGRES_DB: inventory_management
      POSTGRES_USER: bosch
      POSTGRES_PASSWORD: very_secret
    volumes:
      - ./postgres_orchestrator_data:/var/lib/postgresql/data
      - ./helpers/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    environment:
      RABBITMQ_DEFAULT_USER: bosch
      RABBITMQ_DEFAULT_PASS: very_secret
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_logs:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  event_producer:
    build:
      context: .
      dockerfile: Dockerfile
    image: openjdk:17
    environment:
      - JAR_FILE=producer/target/producer-1.0-SNAPSHOT.jar
    depends_on:
      - rabbitmq

  event_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    image: openjdk:17
    environment:
      - JAR_FILE=consumer/target/consumer-1.0-SNAPSHOT.jar
    depends_on:
      - rabbitmq
      - postgres
